language: cpp

os:
    - linux

compiler:
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - gcc --version


before_script:
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install

script:
  - cd ..
  - wget https://fritz.freiburg.de/csv_Downloads/VAGFR.zip && unzip VAGFR.zip
  - wget http://download.geofabrik.de/europe/germany/baden-wuerttemberg/freiburg-regbez-latest.osm.bz2 && bunzip2 freiburg-regbez-latest.osm.bz2
  - pfaedle -D -x freiburg-regbez-latest.osm . -T 1051.T0.11-5-I-z18-1.42.H
  - head trips.txt
  - head shapes.txt
  - cat path.json   
  #- cd gtfs-out
  #- head trips.txt
  #- head shapes.txt
