language: cpp

os:
    - linux

compiler:
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - gcc --version


before_script:
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install

script:
  - cd ..
  - wget https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM_gtfs.zip --output-document=gtfs.zip && unzip gtfs.zip
  - wget http://download.geofabrik.de/europe/france/ile-de-france-latest.osm.bz2 --output-document=data.osm.bz2 && bunzip2 data.osm.bz2
  - pfaedle -D -x data.osm . -T 105892741-1_138104
  - head trips.txt
  #- head shapes.txt
  - cat path.json
  #- cd gtfs-out
  #- head trips.txt
  #- head shapes.txt
