language: cpp

os:
    - linux

compiler:
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - export LD_LIBRARY_PATH=$(if [[ $CXX == "clang++" ]]; then echo -n '/usr/local/clang/lib'; fi)

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - sudo make install

script:
  - cd ..
  - wget https://fritz.freiburg.de/csv_Downloads/VAGFR.zip && unzip VAGFR.zip
  - wget http://download.geofabrik.de/europe/germany/baden-wuerttemberg/freiburg-regbez-latest.osm.bz2 && bunzip2 freiburg-regbez-latest.osm.bz2
  - pfaedle -D -x freiburg-regbez-latest.osm .
  - cd gtfs-out
  - cat shapes.txt
